---
version: '3'

# TODO: systemd + pm2 currently runs pages *2, and systemd runs redis (socket)
# what we want is something that runs in containers instead (+/- node_modules)
services:

  pages:
    command: node api
    environment:
      - LOG_PATH=/tmp/pages.log
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/0
    image: node:12-alpine
    init: true
    ports:
      - 8080:8080/tcp
    restart: always
    user: node
    volumes:
      - .:/home/node/code:ro
    working_dir: /home/node/code

  redis:
    image: library/redis:6-alpine
    ports:
      - 6379:6379/tcp
    restart: always
    volumes:
      - ./data:/data:rw
