---
version: '3'

services:

  pages:
    command: node api
    depends_on:
      - redis
    environment:
      - BIND=127.0.0.1
      - LOG_PATH=/tmp/pages.log
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/0
    image: node:12-alpine
    init: true
    ports:
      - 127.0.0.1:8080:8080/tcp
    restart: always
    user: node
    volumes:
      - .:/home/node/code:ro
    working_dir: /home/node/code

  redis:
    image: library/redis:6-alpine
    ports:
      - 127.0.0.1:6379:6379/tcp
    restart: always
    volumes:
      - ./data:/data:rw
